#############################################################
# Deployment Configuration
#############################################################

PROJECT_NAME="HRMS"

DOCKER_NETWORK="hrms-network"

JENKINS_CONTAINER="jenkins"

SONAR_CONTAINER="sonarqube"

POSTGRES_CONTAINER="postgres"

BACKEND_CONTAINER="hrms-backend"

PROMETHEUS_CONTAINER="prometheus"

GRAFANA_CONTAINER="grafana"

LOKI_CONTAINER="loki"

PROMTAIL_CONTAINER="promtail"

K3S_CLUSTER_NAME="hrms-cluster"
