#############################################################
# Environment Configuration
#############################################################

ENVIRONMENT="development"

AWS_REGION="ap-south-2"

AWS_PROFILE="default"

HOST_IP=""

HOSTNAME="hrms-devops"

TIMEZONE="Asia/Kolkata"

WORKSPACE="/opt/hrms"

LOG_DIR="/var/log/hrms"

BACKUP_DIR="/opt/hrms/backups"
