#############################################################
# Common Variables
#############################################################

GITHUB_REPOSITORY="https://github.com/Kannacse/HRMS-AWS.git"

DEFAULT_BRANCH="main"

JENKINS_HOME="/var/jenkins_home"

DOCKER_SOCKET="/var/run/docker.sock"

TERRAFORM_DIRECTORY="../../Infra"

BACKEND_DIRECTORY="../../Backend/hrms_feb_node/hrms_feb_node"

KUBERNETES_DIRECTORY="../../kubernetes"

MONITORING_DIRECTORY="../../monitoring"

DOCKER_COMPOSE_FILE="../../DevOps/docker-compose.yml"

CUSTOM_JENKINS_IMAGE="custom-jenkins:lts"

BACKEND_IMAGE="hrms-backend:latest"
