#############################################################
# Software Versions
#############################################################

JAVA_VERSION="17"

NODE_VERSION="20"

PYTHON_VERSION="3"

TERRAFORM_VERSION="1.12.2"

KUBECTL_VERSION="stable"

K3S_VERSION="stable"

DOCKER_VERSION="latest"

JENKINS_VERSION="lts"

SONARQUBE_VERSION="lts-community"

POSTGRES_VERSION="15"

PROMETHEUS_VERSION="latest"

GRAFANA_VERSION="latest"

LOKI_VERSION="latest"

PROMTAIL_VERSION="latest"
