version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting HRMS CodeBuild"
      - echo "AWS Region: $AWS_DEFAULT_REGION"
      - echo "Logging into ECR"
      - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

  build:
    commands:
      - echo "Building HRMS backend"
      - docker build -t "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/hrms-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION" Backend/hrms_feb_node/hrms_feb_node

      - echo "Building HRMS frontend"
      - docker build --build-arg BASE_URL="$BASE_URL" -t "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/hrms-frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION" frontend/hrms_feb_flutter

  post_build:
    commands:
      - echo "Pushing backend"
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/hrms-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION"

      - echo "Pushing frontend"
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/hrms-frontend:$CODEBUILD_RESOLVED_SOURCE_VERSION"

      - echo "HRMS images successfully pushed to ECR"
