apiVersion: apps/v1
kind: Deployment

metadata:
  name: hrms-frontend
  namespace: hrms

spec:
  replicas: 1

  selector:
    matchLabels:
      app: hrms-frontend

  template:
    metadata:
      labels:
        app: hrms-frontend

    spec:
      containers:
        - name: hrms-frontend
          image: kannancloud/hrms-frontend:25
          imagePullPolicy: Always

          ports:
            - containerPort: 80
