apiVersion: v1
kind: Secret

metadata:
  name: hrms-secret
  namespace: hrms

type: Opaque

stringData:

  DB_HOST: mysql

  DB_PORT: "3306"

  DB_NAME: hrms

  DB_USER: root

  DB_PASSWORD: password
