apiVersion: v1
kind: Service
metadata:
  name: hrms-backend-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: hrms-backend

  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}

  type: {{ .Values.backend.service.type }}
