apiVersion: v1
kind: Secret
metadata:
  name: hrms-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secret.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | quote }}
  REFRESH_SECRET_KEY: {{ .Values.secret.refreshSecretKey | quote }}
