apiVersion: apps/v1
kind: Deployment

metadata:
  name: hrms-backend
  namespace: hrms

spec:
  replicas: 3

  selector:
    matchLabels:
      app: hrms-backend

  template:
    metadata:
      labels:
        app: hrms-backend

    spec:
      containers:
        - name: hrms-backend
          image: nginx:latest

          ports:
            - containerPort: 80
