apiVersion: v1
kind: Secret
metadata:
  name: hrms-secret
  namespace: hrms
type: Opaque
stringData:
  DB_USER: root
  DB_PASSWORD: root123
  SECRET_KEY: change_this_to_a_long_random_secret
  REFRESH_SECRET_KEY: change_this_to_another_random_secret
